### PR TITLE
Add travis and coveralls support

### PR DESCRIPTION
**Pull request by seanwiseman**
Just focus on the files changed, I did not delete previous branch (my bad) so it shows previous commits as well for the `initial implementation` PR, though its whats currently in `master`.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Travis CI: throughout the last year we have centralized builds on Jenkins as it deals with projects and deployments, and is faster due to the dedicated hardware (13 seconds vs 41 seconds in this case). `Build passing` badges are covered like in https://github.com/elifesciences/journal#elife-journal so what's the use case for building the project twice in two different places?

Coveralls is pretty standard across Python projects, we add authorization tokens to https://github.com/elifesciences/builder-private/blob/23846d44e98bea62fa191180b1100b3d7a373433/pillar/elife-libraries.sls#L7-L12
and pass them as an env variable like in https://github.com/elifesciences/elife-tools/blob/develop/project_tests.sh#L9
I'm not sure who has the permission to create a token for a particular project.

**Comment by seanwiseman** [comment]
Re Coveralls, that's fine I will add a token for both, just checked and I can make them.

Re Travis, I was just following the pattern used in https://github.com/elifesciences/elife-tools . As for a use case, I suppose people who are not authorised to see the Jenkins build history (not sure if this is the case) could see the Travis history? also this may just be down to the environment, but Travis actually revealed a `boto3` exception during testing (just required another mock.patch in the test suite) that was passing locally for me and through Jenkins. Though this may just be an edge case.

Not fussed if we don't use Travis, but just saw other elife projects using it so I thought I would add it as I use it on personal projects.

**Comment by giorgiosironi** [comment]
(The current authorization strategy is that anyone inside the `elifesciences` organization has full read access, everyone outside it can only see job statuses like badges but not outputs)

**Comment by seanwiseman** [comment]
OK will loose Travis and put a PR in for the Coveralls tokens.

**Comment by seanwiseman** [comment]
@giorgiosironi  OK to merge this now?

**Pull request merged**
